# NeoOS musl build
#
# Builds upstream musl (git://git.musl-libc.org/musl, vendored as a
# pristine submodule at upstream/) with the NeoOS syscall shim applied,
# then exposes the result under build-output/ per the org's build
# contract. This is the same `musl` target the old NeoOS monorepo used
# --  same configure line, same shim application, same headers -- just
# relocated to its own repo.

KERNEL_SHIM_DIR ?= ../neoos-kernel/third_party/shim
UPSTREAM_DIR    ?= upstream
PREFIX          ?= build-output
CROSS_DIR       ?= $(HOME)/opt/cross-x86_64-elf/bin
# Plain `=`, not `?=`: Make predefines CC and AR from its built-in
# rules, so a conditional assignment silently loses to Make's own
# "cc"/"ar" defaults instead of picking up the cross-compiler. A
# command-line override (`make CC=...`) still wins over either form.
CC              = $(CROSS_DIR)/x86_64-elf-gcc
AR              = $(CROSS_DIR)/x86_64-elf-ar
RANLIB          ?= $(CROSS_DIR)/x86_64-elf-ranlib

MUSL_LIB     := $(UPSTREAM_DIR)/lib/libc.a
SHIM_SOURCES := $(wildcard $(KERNEL_SHIM_DIR)/*.c $(KERNEL_SHIM_DIR)/*.h $(KERNEL_SHIM_DIR)/*.s) $(KERNEL_SHIM_DIR)/apply.sh

.PHONY: all clean

all: $(PREFIX)/lib/libc.a

# Idempotent: apply.sh only ever touches the same seven files inside
# upstream/, keeping .orig backups, so re-running on an unchanged shim
# is a no-op and upstream/ stays a pristine checkout apart from those
# seven files -- exactly as it did inside the old monorepo.
$(MUSL_LIB): $(SHIM_SOURCES)
	@[ -d "$(KERNEL_SHIM_DIR)" ] || { \
		echo "KERNEL_SHIM_DIR not found: $(KERNEL_SHIM_DIR)" >&2; \
		echo "Clone neoos-kernel next to this repo, or set KERNEL_SHIM_DIR=/path/to/its/third_party/shim" >&2; \
		exit 1; }
	MUSL_DIR=$(abspath $(UPSTREAM_DIR)) $(KERNEL_SHIM_DIR)/apply.sh
	cd $(UPSTREAM_DIR) && ./configure --target=x86_64 --disable-shared \
		CC=$(CC) AR=$(AR) RANLIB=$(RANLIB) \
		CFLAGS="-mcmodel=large -fno-pic -mno-red-zone -O2" >/dev/null
	$(MAKE) -C $(UPSTREAM_DIR) -j$(shell nproc) >/dev/null

# musl's own build leaves headers split across four directories
# (include/, arch/x86_64/, arch/generic/, obj/include/ -- the last
# generated by configure), isystem'd by consumers in that priority
# order. build-output exposes each as its own symlink rather than
# merging them into one: merging would have to reproduce that priority
# order file-by-file, and getting it wrong would look like a passing
# build with silently wrong headers.
$(PREFIX)/lib/libc.a: $(MUSL_LIB)
	mkdir -p $(PREFIX)
	ln -sfn $(abspath $(UPSTREAM_DIR)/lib)          $(PREFIX)/lib
	ln -sfn $(abspath $(UPSTREAM_DIR)/include)      $(PREFIX)/include
	ln -sfn $(abspath $(UPSTREAM_DIR)/arch/x86_64)  $(PREFIX)/include-arch-x86_64
	ln -sfn $(abspath $(UPSTREAM_DIR)/arch/generic) $(PREFIX)/include-arch-generic
	ln -sfn $(abspath $(UPSTREAM_DIR)/obj/include)  $(PREFIX)/include-obj

clean:
	rm -f $(PREFIX)/lib $(PREFIX)/include $(PREFIX)/include-arch-x86_64 \
	      $(PREFIX)/include-arch-generic $(PREFIX)/include-obj
	rmdir $(PREFIX) 2>/dev/null || true
	cd $(UPSTREAM_DIR) && git checkout -- . && git clean -fdx
